- name: Create and apply kernel config
  shell: |
    touch {{ project_root }}/settings/100-isucon.conf
    sudo cp -f {{ project_root }}/settings/100-isucon.conf /etc/sysctl.d/100-isucon.conf
    sudo sysctl -p /etc/sysctl.d/100-isucon.conf >> /dev/null
  args:
    chdir: "{{ project_root }}/settings"
