- name: git config
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: user.name
      value: "{{ git.username }}"
    - name: user.email
      value: "{{ git.email }}"

- name: Create git repository
  shell: |
    git init
    git remote add origin {{ git.repo }}
  args:
    chdir: "{{ project_root }}"

# TODO: 編集方法
- name: Set gitignore
  shell: |
    find ./ -size +100M >> .gitignore
    nano .gitignore
  args:
    chdir: "{{ project_root }}"
