- name: git config
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: user.name
      value: "{{ git.username }}"
    - name: user.email
      value: "{{ git.email }}"
    - name: safe.directory
      value: "{{ project_root }}"

- name: Create git repository
  shell: |
    git init
  args:
    chdir: "{{ project_root }}"

- name: Add git remote repository
  shell: |
    git remote add origin {{ git.repo }}
  args:
    chdir: "{{ project_root }}"
  ignore_errors: true

# TODO: エディタでの編集方法
- name: Set gitignore
  shell: |
    find ./ -size +100M >> .gitignore
  args:
    chdir: "{{ project_root }}"
