- name: git config
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: user.name
      value: "$(GIT_USERNAME)"
    - name: user.email
      value: "$(GIT_EMAIL)"

- name: Create git repository
  shell: |
    git init
    git remote add origin $(GIT_REPO)
  args:
    chdir: "$(PROJECT_ROOT)"

# TODO: 編集方法
- name: Set gitignore
  shell: |
    find ./ -size +100M >> .gitignore
    nano .gitignore
  args:
    chdir: "$(PROJECT_ROOT)"
