- name: git pull
  shell: |
    git pull origin main
    curl -X POST -H "Content-type: application/json" -d '{"content": "サーバーへ現在のリポジトリをプルしました。"}' {{ discord_webhook_url }} -s -o /dev/null
  args:
    chdir: "{{ project_root }}"
