- name: Import MySQL config
  shell: |
    sudo cp -r -i /etc/mysql/ {{ project_root }}/settings/mysql/
    curl -X POST -H "Content-type: application/json" -d '{"content": "MySQL/MariaDBの設定ファイルをコピーしました。"}' {{ discord_webhook_url }} -s -o /dev/null
  args:
    chdir: "{{ project_root }}/settings"
