- name: Install MySQL
  apt:
    name:
      - mysql-server
      - mysql-client
    state: latest
    update_cache: true

- name: Set up MySQL
  shell: |
    sudo mysql -e "CREATE USER IF NOT EXISTS '{{ db.user }}'@'localhost' IDENTIFIED BY '{{ db.pass }}'"
    sudo mysql -e "GRANT ALL PRIVILEGES ON * . * TO '{{ db.user }}'@'localhost';"
    sudo mysql -e "FLUSH PRIVILEGES;"
    sudo mysql -e "CREATE DATABASE {{ db.name }};"
    curl -X POST -H "Content-type: application/json" \
      -d '{"content": "MySQLを正常にインストールし、ユーザー「{{ db.user }}」・データベース「{{ db.name }}」を作成しました。"}' {{ discord_webhook_url }} -s -o /dev/null
    sudo systemctl status mysql
    mysql --version

# - name: Install MariaDB
#   shell: |
#     sudo apt update && sudo apt-get install mariadb-client mariadb-server -y
#     sudo mysql -e "CREATE USER IF NOT EXISTS '{{ db.user }}'@'localhost' IDENTIFIED BY '{{ db.pass }}'"
#     sudo mysql -e "GRANT ALL PRIVILEGES ON * . * TO '{{ db.user }}'@'localhost';"
#     sudo mysql -e "FLUSH PRIVILEGES;"
#     sudo mysql -e "CREATE DATABASE {{ db.name }};"
#     curl -X POST -H "Content-type: application/json" \
#       -d '{"content": "MariaDBを正常にインストールし、ユーザー「{{ db.user }}」・データベース「{{ db.name }}」を作成しました。"}' {{ discord_webhook_url }} -s -o /dev/null
#     sudo systemctl status mysql
#     mariadb --version
