- name: mysql allow ex
  shell: |
    sudo mysql -e "SELECT user, host FROM mysql.user;"
    sudo mysql -e "RENAME USER '{{ db.user }}'@'localhost' TO '{{ db.user }}'@'%';"
    make reset-mysql
    sudo mysql -e "SELECT user, host FROM mysql.user;"
    curl -X POST -H "Content-type: application/json" \
      -d '{"content": "MySQL/MariaDBのユーザーへの外部からのアクセスを許可しました。`bind_address`が`0.0.0.0`になっていることを確かめてください。"}' {{ discord_webhook_url }} -s -o /dev/null

- name: Get DB sample
  shell: |
    $(eval TABLES := $(shell mysql -h$(DB_HOST) -P{{ db.port }} -u{{ db.user }} -p{{ db.pass }} {{ db.name }} -e 'SHOW TABLES;' -sN))
    echo "Data Samples" > /temp/sample.txt
    for table in $(TABLES); do \
      echo "" >> /temp/sample.txt && \
      echo "-----$$table-----" >> /temp/sample.txt && \
      mysql -h{{ db.host }} -P{{ db.port }} -u{{ db.user }} -p{{ db.pass }} {{ db.name }} -t -e "SELECT * FROM $$table LIMIT 10;" >> /temp/sample.txt; \
    done
    curl -X POST -F txt=@/temp/sample.txt {{ discord_webhook_url }} -s -o /dev/null

- name: Get DB status
  shell: |
    echo "-----CPU Info-----" > /temp/status.txt
    grep processor /proc/cpuinfo >> /temp/status.txt && echo "" >> /temp/status.txt
    echo "-----Memory Info-----" >> /temp/status.txt
    free -h >> /temp/status.txt && echo "" >> /temp/status.txt
    echo "-----Service Info-----" >> /temp/status.txt
    systemctl list-units --type=service --state=running >> /temp/status.txt && echo "" >> /temp/status.txt
    echo "-----DB Table & Column Info-----" >> /temp/status.txt
    mysql -h{{ db.host }} -P{{ db.port }} -u{{ db.user }} -p{{ db.pass }} -t \
      -e 'USE information_schema; SELECT table_name, column_name FROM columns WHERE table_schema="{{ db.name }}";' >> /temp/status.txt
    curl -X POST -F txt=@/temp/status.txt {{ discord_webhook_url }} -s -o /dev/null
