- name: build
  shell: |
    go build -o {{ build_name }}
  args:
    chdir: "{{ go_project_root }}"

- name: deploy
  shell: |
    sudo systemctl stop {{ systemctl_service }}
    sudo rm -f /etc/systemd/system/{{ systemctl_service }}.service
    sudo cp {{ project_root }}/settings/{{ systemctl_service }}.service /etc/systemd/system/
    sudo systemctl start {{ systemctl_service }}
    sudo systemctl daemon-reload
