- name: apt update
  apt:
    update_cache: yes

# すげー時間掛かる
# - name: apt upgrade
#   apt:
#     upgrade: yes

# --add-host="archive.ubuntu.com:160.26.2.187"
- name: Install common packages
  apt:
    name:
      - htop
      - dstat
      - graphviz
    state: latest
    update_cache: yes
