- name: set hostname
  become: true
  hostname:
    name: "{{ hostname }}"

- import_tasks: apt.yml
- import_tasks: setup.yml
- import_tasks: ./roles/git/tasks/create.yml
- import_tasks: install.yml
- import_tasks: import.yml
- import_tasks: ./roles/git/tasks/push.yml

- name: Restart
  shell: |
    curl -X POST -H "Content-type: application/json" -d '{"content": "サーバーを再起動します。再起動後にプッシュしてください。"}' {{ discord_webhook_url }} -s -o /dev/null
    sudo shutdown -r now
  ignore_errors: true
