- name: Uninstall golang
  apt:
    name: golang
    state: absent

- name: Install golang
  shell: |
    $(eval GO_CUR_PATH := $(shell which go | sed 's/\/bin\/go//'))
    sudo rm -rf {{ go_cur_path }}
    wget -P /temp https://go.dev/dl/go${GO_LATEST_VERSION}.linux-amd64.tar.gz
    sudo tar -C {{ go_cur_path }} /temp/go${GO_LATEST_VERSION}.linux-amd64.tar.gz
    rm /temp/go${GO_LATEST_VERSION}.linux-amd64.tar.gz
