- name: git pull
  import_tasks: ./roles/git/tasks/pull.yml

- name: Apply reverse proxy
  import_tasks: ./roles/reverse_proxy/tasks/apply.yml

- name: Apply DB
  import_tasks: ./roles/db/tasks/apply.yml

- name: Apply env
  import_tasks: ./roles/application/tasks/apply.yml

- name: Apply kernel
  import_tasks: ./roles/kernel/tasks/apply.yml

- name: Apply netdata
  import_tasks: ./roles/netdata/tasks/apply.yml

- name: deploy
  import_tasks: ./roles/application/tasks/main.yml
